// <auto-generated />
namespace hospital_project4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Feetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202304122353183_Fee-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
